---
layout: cv
title: Kiersten Bicmore's CV
---
# Kiersten Bickmore
Student at Brigham Young University - Idaho

<div id="webaddress">
<a href="bic19001@byui.edu">bic19001@byui.edu</a>
| <a href="www.linkedin.com/in/kiersten-bickmore-29b8bb211">LinkedIn Page</a>
</div>


## Currently

I am currently a student attending Brigham Young University - Idaho majoring in Professional Studies with a minor in data science and a cluster in math. 

### Specialized in

I have had a few different kinds of work experience and the ability to learn new skills from each position. Some of these skills include customer service, training new employees, prepping ingredients to create orders to customer specifications, taking inventory and recording numbers, and researching information to report. Different experiences have given me useful skills to use in my daily life, one skill being communication gained from speaking in front of large groups. I have grown to use both Adobe Photoshop and Microsoft Office products effectively and efficiently.


## Education

`September 2019 - Current`
__Brigham Young University – Idaho__

`August 2017 - May 2019`
__Chattahoochee High School__

## Work Experience

__Custodian__
`March 2023 - July 2024`
- Custodian - Cleaned several areas, including bathrooms and offices
- Trainer - Explained daily procedure to new employees
- Inventory/Stocker - Organized and took count of the number of items in each closet; stocked items
that were running low

__Sanitizer__
`January 2022 - April 2022`
- Sanitizer - Walked around sanitizing areas; cleaned any areas that were out of order/dirty
- Inventory/Stocker - Organized and took count of the number of items in each closet; stocked items
that were running low for the morning crew

__Domino's Pizza Customer Service Representative__
`January 2021 - April 2021`
- Cashier/Customer Service - Informed customers about different products, calculated purchase totals
for customers and verified prices; addressed concerns and complaints with products
- Food Prep - Stocked food supplies for pizza, sandwiches, and pasta, prepared food samples for
customers, prepared meals for customer orders

__Inventory/Reporter__
`February 2020 - Spetember 2020`
- Inventory/Reporter - Organized and took count of the number of items in each unit; reported said
numbers and other information to employer
- Starter - Arrived at storage units at planned time to work
- Researcher - Researched prices of medical equipment and recorded numbers on Excel

__Great Harvest Bread Company__
`August 2018 - May 2019`
- Cashier/Customer Service - Informed customers about different products, calculated
purchase totals for customers and verified prices, gaining experience in customer
interaction and clerical skills; addressed concerns and complaints with products
- Trainer - Explained daily procedure to new employees
- Closer – Store facility maintenance
- Food Prep – Stocked food supplies for sandwiches, prepared food samples for
customers, prepared meals for customer orders

<!-- ### Footer

Last updated: December 2024 -->